### PR TITLE
Feature: Add support for 16 port switches and naming

### PR DESCRIPTION
**Pull request by catduckgnaf**
Feature:

Add support for 16 port HDMI Switches.
Add Feature ability to name sources in configuration

  - platform: tesmart_kvm
    kvms:
      tesmart_hdmi_switch:
        friendly_name: Nerdroom HDMI Switch
        host: !secret hdmi_switch_nerdroom_host
        sources:
          HDMI 1: NES
          HDMI 2:  SENES
          HDMI 3: Xbox One
          HDMI 4: HDMI 4
          HDMI 5: HDMI 5
          HDMI 6: HDMI 6
          HDMI 7: HDMI 7
          HDMI 8: HDMI 8
          HDMI 9: HDMI 9
          HDMI 10: HDMI 10
          HDMI 11: HDMI 11
          HDMI 12: HDMI 12
          HDMI 13: HDMI 13
          HDMI 14: HDMI 14
          HDMI 15: HDMI 15
          HDMI 16: HDMI 16

Potential Breaking Change:
I removed volume/mute because I did not see that supported?

### CODE REVIEW

**Comment by AliceDiNunno** [comment]
Actually Volume/mute was referring to the beeper of the unit so you can enable or disable it

**Comment by catduckgnaf** [comment]
> Actually Volume/mute was referring to the beeper of the unit so you can enable or disable it

Ahhhhh! That makes sense.
Do you think that would be more useful as a config option? I guess doesn't hurt to leave it.

I can add it back. 

Let me know thoughts on other changes, it's working great on my HDMI 16 switcher. I can rename and ignore sources perfectly.

**Comment by AliceDiNunno** [comment]
Yeah a config option would be perfect !

**Comment by catduckgnaf** [comment]
> Yeah a config option would be perfect !
@AliceDiNunno take a look when you get a chance. I went through and renamed to tesmart_lan added documentation, with list of supported devices. I almost didn't buy my hdmi switch, was curious if this was only for "KVMs" 
Also, for audio, I made it under media_player entity as a sound mode. Beeper on or off. So when you click entity in UI if gives you the option, just under sources.
Also should save source and beeper states, while leaving beeper off to default.

**Comment by lululombard** [comment]
@catduckgnaf thank you so much for your work, I added you as a collaborator and I'm merging this PR :)

**Review by lululombard — APPROVED** [review]

**Comment by catduckgnaf** [comment]
> @catduckgnaf thank you so much for your work, I added you as a collaborator and I'm merging this PR :)

This made my day! Thank you so much, glad you liked the changes.

**Pull request merged**
